- name: Install Chrony
  package:
    name: chrony
    state: present

- name: Configure Chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: 0644
  notify: restart chronyd

- name: Enable chronyd
  service:
    name: chronyd
    enabled: true

- name: Change timezone
  shell: timedatectl set-timezone {{ timezone }}
